### PR TITLE
Add season 2 weapons

### PR DESCRIPTION
**Pull request by paulhoenhorst**
**Added new season 2 weapons:**

- AR: BP50
- SMG: RAM-9

### CODE REVIEW

**Comment by paulhoenhorst** [comment]
I'm currently working on it as I don't have the camos yet.

**Comment by paulhoenhorst** [comment]
I will add the BP50 later. Need a bit to unlock it

**Comment by seanogdev** [comment]
Could we merge with placeholder camos?

**Comment by paulhoenhorst** [comment]
> Could we merge with placeholder camos?

If @carlssonemil merge it should automatically add placeholders.

**Review by carlssonemil — APPROVED** [review]
I'll upload the camos from this PR tomorrow!

**Comment by matt-whiteley** [comment]
@carlssonemil should this have auto deployed when it was merged? I cannot see these guns on the tracker yet.

**Comment by carlssonemil** [comment]
@matt-whiteley, they needed to be added to another array to visibly show up in the app, I forgot to check that they were added there in this PR 🙈 I've added them now and they should be visible in the app momentarily! Thanks for pointing it out! 🎉

**Comment by matt-whiteley** [comment]
Nice!

Looks like the requirements are not pulling through, I will take a look at that and open a PR with the fix.

How are people getting the camo images? Extracting them from the pc game files?

**Pull request merged**
